development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Lyricist
  admin_email: mailer@lyricistapp.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://lyricistapp.com
  site_name: Lyricist
  admin_email: mailer@lyricistapp.com
  
production:
  site_url: http://lyricistapp.com
  site_name: Lyricist
  admin_email: mailer@lyricistapp.com
